name: trippybug_CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Check Node.js version
        run: node --version

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "20"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Verify build success
        run: |
          if [ -d ".next" ]; then
            echo "Build successful!"
          else
            echo "Build failed! Exiting..."
            exit 1
          fi
